'use client';
import Skill from "../../components/skill";
import Aboutme from "../../components/aboutme";
import Portfo from "../../components/portfolio"
import Footer from "../../components/Footer";


import Head from "next/head";
import React, { useState, useEffect } from "react";
import { BsFillMoonStarsFill, BsFillSunFill } from "react-icons/bs";
import {
  AiFillGithub,
  AiFillLinkedin,
  AiFillInstagram,
} from "react-icons/ai";
import Image from "next/image";

import Buuuu from "public/Buuuu.png";
import Buuuu_w from "public/Buuuu-w.png";
import logo from "public/logo.png";
import logo_w from "public/logo-w.png";
import Skills from "public/Skills.png";
import Skills_w from "public/Skills-w.png";
import Portfolio from "public/Portfolio.png";
import Portfolio_w from "public/Portfolio-w.png";
import about from "public/AboutMe.png";
import about_w from "public/AboutMe-w.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // Simulating a delay of 2 seconds
    setTimeout(() => {
      setIsLoading(false);
    }, 2000);
  }, []);

  return (
    <div className={darkMode ? "dark" : ""}>
      {isLoading ? (
        <div className="flex items-center justify-center h-screen bg-white">
          <div className="flex">

            <div className="h-3 w-3 bg-gray-900 dark:bg-white rounded-full mr-1 animate-bounce"></div>
            <div className="h-3 w-3 bg-gray-900 dark:bg-white rounded-full mr-1 animate-bounce"></div>
            <div className="h-3 w-3 bg-gray-900 dark:bg-white rounded-full mr-1 animate-bounce"></div>

          </div>
        </div>
      ) : (

        <div>
          <Head>
            <title>Anas's Portfolio</title>
            <meta name="description" content="Generated by create next app" />
          </Head>
          <main className="bg-white text-black px-10 md:px-20 lg:px-60 dark:bg-neutral-900 dark:text-white">
            <section className=" min-h-screen ">
              <nav className="py-10 mb-12 flex justify-between ">
                <div className="w-10">
                  <Image src={darkMode ? logo_w : logo} />
                </div>
                <ul className="flex items-center">
                  <li>
                    <BsFillMoonStarsFill
                      onClick={() => setDarkMode(!darkMode)}
                      className='cursor-pointer text-2xl  dark:hidden'
                    />
                  </li>
                  <li>
                    <BsFillSunFill
                      onClick={() => setDarkMode(!darkMode)}
                      className='cursor-pointer text-2xl hidden  dark:block'
                    />
                  </li>
                  {/*  <li className="text-white bg-gradient-to-r from-zinc-900 to-zinc-700 dark:from-slate-50 dark:to-slate-200 dark:text-zinc-900 px-4 py-2 rounded-md ml-8">
              Resume
  </li>*/}
                </ul>
              </nav>
              <div className="text-center pt-20 lg:pt-11">


                <div className="relative mx-auto w-[290px] lg:w-[480px] ">
                  <Image src={darkMode ? Buuuu_w : Buuuu} />
                </div>

              </div>
              <div className="flex text-3xl justify-center mt-6 lg:gap-16 gap-11 py-6 text-zinc-900 dark:text-white">
                <a href="https://github.com/anasbounaiim" target="_blank"><AiFillGithub /></a>
                <a href="https://www.linkedin.com/in/anas-bounaim-37450621a/" target="_blank"> <AiFillLinkedin /></a>
                <a href="https://www.instagram.com/anasbounaiim/" target="_blank"> <AiFillInstagram /></a>
              </div>

              <hr className="my-28 w-44  m-auto lg:w-[300px]" />
            </section>

            <div className="w-48 lg:w-[450px] py-5">
              <Image src={darkMode ? about_w : about} />
            </div>
            <Aboutme></Aboutme>


            <div className="w-48 lg:w-72 py-5">
              <Image src={darkMode ? Skills_w : Skills} />
            </div>

            <Skill></Skill>

            <div className="w-52 lg:w-80 py-5">
              <Image src={darkMode ? Portfolio_w : Portfolio} />
            </div>

            <Portfo></Portfo>


          </main>
          <Footer></Footer>
        </div>

      )}

    </div>
  );
}
